### ISSUE TITLE
Does the query data have to be included in the data for constructing an inverted index?

### ISSUE THREAD

**Issue by chunjiangzhu** [idea-iitd/RISC#1]
Hi authors,

We encountered a runtime error "binaryFingerPrint.c (line 218) invalid feature values". It appears only for some specific querying data. Do you have any suggestions on this error? Do we have to put the query data into the base data for constructing an inverted index?

Thank you so much!
Regards,
Chunjiang

**Comment by jithinvachery** [comment]
Hi,

1) We do not require that the query data be part of index construction phase
2) We do require that all the features of a query be present in the data used in index construction. Hence, if some query point has a feature which was not part of index construction, it throws an error.
3) We shall fix this in the next version.

Regards,
Jithin

**Comment by chunjiangzhu** [comment]
Got it. Thank you for your explanation!
Chunjiang
